#pragma once


#define TILE_OBJ_COUNT 19
#define TOKEN_OBJ_COUNT_PER 3

#define OBS_TOKEN_FIRST_ARRANGE 0
#define OBS_TOKEN_POS_IMPOSSIBLE 1
#define OBS_TOKEN_POS_POSSIBLE 2
#define OBS_TOKEN_MOVE 3
#define OBS_TILE_FIRST_ARRANGE 4
#define OBS_TILE_POS_IMPOSSIBLE 5
#define OBS_TILE_POS_POSSIBLE 6
#define OBS_TILE_MOVE 7