#pragma once

#define SHADER_REG_PS_CB_DIRECTIONAL_LIGHT 0
#define SHADER_REG_PS_CB_POINT_LIGHT 1
#define SHADER_REG_PS_CB_SPOT_LIGHT 2
#define SHADER_REG_PS_CB_EYE 3
#define SHADER_REG_PS_CB_MATERIAL 4
#define SHADER_REG_PS_CB_LIGHTVP 5

#define SHADER_REG_PS_SRV_CM 0
#define SHADER_REG_PS_SRV_DIFFUSE 1
#define SHADER_REG_PS_SRV_NORMAL 2
#define SHADER_REG_PS_SRV_SHADOW 3
#define SHADER_REG_PS_SRV_SSAO 4

#define SHADER_REG_PS_SAMP_CM 0
#define SHADER_REG_PS_SAMP_TEX 1
#define SHADER_REG_PS_SAMP_SHADOW 2