#pragma once

#define TILE_OBJ_COUNT 19
#define TOKEN_OBJ_COUNT_TOTAL 6
#define TOKEN_OBJ_COUNT_PER 3
#define TILE_SPACE_COUNT_X 25
#define TILE_SPACE_COUNT_Z 25
#define TILE_SPACE_INTERVAL_X 10.0f
#define TILE_SPACE_INTERVAL_Z 12.0f